"""Added aircall_number column in call records table

Revision ID: 158f7ca8caab
Revises: 35e56fddda43
Create Date: 2025-01-04 20:02:57.507135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158f7ca8caab'
down_revision = '35e56fddda43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aircall_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_record', schema=None) as batch_op:
        batch_op.drop_column('aircall_number')

    # ### end Alembic commands ###
