"""Added Client table

Revision ID: 1619a711a264
Revises: 967cb3536518
Create Date: 2024-10-17 23:45:08.445417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1619a711a264'
down_revision = '967cb3536518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email_password', sa.String(length=50), nullable=True),
    sa.Column('email_server', sa.String(length=20), nullable=True),
    sa.Column('bank_username', sa.String(length=50), nullable=False),
    sa.Column('bank_password', sa.String(length=50), nullable=False),
    sa.Column('bank_form', sa.String(length=20), nullable=True),
    sa.Column('aircall_id', sa.String(length=50), nullable=True),
    sa.Column('aircall_key', sa.String(length=50), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('is_bank_connected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], name=op.f('fk_client_agency_id_agency')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client'))
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_agency_id'), ['agency_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_agency_id'))

    op.drop_table('client')
    # ### end Alembic commands ###
