"""Added fetch date table in Campaign table

Revision ID: 35e56fddda43
Revises: 825f7fca290a
Create Date: 2024-12-29 00:23:56.640195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e56fddda43'
down_revision = '825f7fca290a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fetch_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('fetch_date')

    # ### end Alembic commands ###
