"""Added BankTransaction table

Revision ID: 464ee6c55489
Revises: 1f0fb8d020e2
Create Date: 2024-10-17 23:47:10.543733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464ee6c55489'
down_revision = '1f0fb8d020e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finapi_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(precision=3), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name=op.f('fk_bank_transaction_lead_id_lead')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bank_transaction'))
    )
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transaction_lead_id'), ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaction_lead_id'))

    op.drop_table('bank_transaction')
    # ### end Alembic commands ###
