"""updated delete for relationship

Revision ID: 61323ffd2fb3
Revises: 158f7ca8caab
Create Date: 2025-01-25 23:53:28.084777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61323ffd2fb3'
down_revision = '158f7ca8caab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bank_transaction_finapi_id'), ['finapi_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transaction_finapi_id'))

    # ### end Alembic commands ###
