"""Added MailInvoice table

Revision ID: 7c7f5bfa21aa
Revises: 464ee6c55489
Create Date: 2024-10-21 20:12:56.638784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7f5bfa21aa'
down_revision = '464ee6c55489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_id', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(precision=3), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], name=op.f('fk_mail_invoice_lead_id_lead')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mail_invoice'))
    )
    with op.batch_alter_table('mail_invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mail_invoice_lead_id'), ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mail_invoice_lead_id'))

    op.drop_table('mail_invoice')
    # ### end Alembic commands ###
